spring.application.name=medical-billing-backend

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:2025/medical_billing
spring.datasource.username=root
spring.datasource.password=Root@123
spring.security.user.name=admin
spring.security.user.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=ReplaceWithYourVeryLongRandomSecretKeyForDevelopmentOnly
jwt.expiration=86400000